import type { AppDefinition } from "./types";

export const STORAGE_PREFIX = "os-folio";

export const STORAGE_KEYS = {
  theme: `${STORAGE_PREFIX}:theme`,
  accent: `${STORAGE_PREFIX}:accent`,
  brightness: `${STORAGE_PREFIX}:brightness`,
  wallpaperId: `${STORAGE_PREFIX}:wallpaper-id`,
  customWallpaper: `${STORAGE_PREFIX}:wallpaper-custom`,
} as const;

export const DEFAULT_THEME = {
  mode: "light" as const,
  accent: "green" as const,
  brightness: 100,
  wallpaperId: "theme-solid",
  customWallpaperUrl: null,
};

export const ACCENT_COLORS = [
  { id: "orange" as const, label: "Orange", hex: "#ea580c" },
  { id: "green" as const, label: "Green", hex: "#5fa85f" },
  { id: "blue" as const, label: "Blue", hex: "#5087d4" },
  { id: "purple" as const, label: "Purple", hex: "#a172cf" },
];

export const APP_REGISTRY: Record<string, AppDefinition> = {
  about: {
    id: "about",
    title: "About",
    icon: "📄",
    defaultWidth: 500,
    defaultHeight: 700,
    defaultX: 280,
    defaultY: 60,
    showInExplorer: true,
    showInTaskbar: true,
  },
  works: {
    id: "works",
    title: "Works",
    icon: "🗂️",
    defaultWidth: 1080,
    defaultHeight: 680,
    defaultX: 240,
    defaultY: 40,
    showInExplorer: true,
    showInTaskbar: true,
  },
  experience: {
    id: "experience",
    title: "Experience",
    icon: "💼",
    defaultWidth: 780,
    defaultHeight: 680,
    defaultX: 300,
    defaultY: 50,
    showInExplorer: true,
    showInTaskbar: true,
  },
  blog: {
    id: "blog",
    title: "Blog",
    icon: "📝",
    defaultWidth: 1000,
    defaultHeight: 640,
    defaultX: 260,
    defaultY: 40,
    showInExplorer: true,
    showInTaskbar: true,
  },
  contact: {
    id: "contact",
    title: "Contact",
    icon: "✉️",
    defaultWidth: 500,
    defaultHeight: 700,
    defaultX: 340,
    defaultY: 80,
    showInExplorer: true,
    showInTaskbar: true,
  },
  terminal: {
    id: "terminal",
    title: "Terminal",
    icon: "⬛",
    defaultWidth: 920,
    defaultHeight: 560,
    defaultX: 220,
    defaultY: 80,
    showInExplorer: true,
    showInTaskbar: true,
  },
  settings: {
    id: "settings",
    title: "Settings",
    icon: "⚙️",
    defaultWidth: 920,
    defaultHeight: 640,
    defaultX: 240,
    defaultY: 50,
    showInExplorer: true,
    showInTaskbar: true,
  },
  help: {
    id: "help",
    title: "Help",
    icon: "❓",
    defaultWidth: 860,
    defaultHeight: 620,
    defaultX: 260,
    defaultY: 60,
    showInExplorer: true,
    showInTaskbar: true,
  },
  search: {
    id: "search",
    title: "Search",
    icon: "🔍",
    defaultWidth: 640,
    defaultHeight: 480,
    defaultX: 320,
    defaultY: 100,
    showInExplorer: true,
    showInTaskbar: true,
  },
  "folder-germany": {
    id: "folder-germany",
    title: "germany",
    icon: "📁",
    defaultWidth: 780,
    defaultHeight: 560,
    defaultX: 260,
    defaultY: 50,
    showInExplorer: false,
    showInTaskbar: true,
  },
  "folder-austria": {
    id: "folder-austria",
    title: "austria",
    icon: "📁",
    defaultWidth: 780,
    defaultHeight: 560,
    defaultX: 280,
    defaultY: 70,
    showInExplorer: false,
    showInTaskbar: true,
  },
  "folder-india": {
    id: "folder-india",
    title: "india",
    icon: "📁",
    defaultWidth: 780,
    defaultHeight: 560,
    defaultX: 300,
    defaultY: 90,
    showInExplorer: false,
    showInTaskbar: true,
  },
  "about-txt": {
    id: "about-txt",
    title: "about.txt",
    icon: "📄",
    defaultWidth: 760,
    defaultHeight: 520,
    defaultX: 240,
    defaultY: 30,
    showInExplorer: false,
    showInTaskbar: true,
  },
  "build-log-md": {
    id: "build-log-md",
    title: "build-log.md",
    icon: "📄",
    defaultWidth: 760,
    defaultHeight: 520,
    defaultX: 260,
    defaultY: 50,
    showInExplorer: false,
    showInTaskbar: true,
  },
  "llm-txt": {
    id: "llm-txt",
    title: "llm.txt",
    icon: "📄",
    defaultWidth: 760,
    defaultHeight: 520,
    defaultX: 280,
    defaultY: 70,
    showInExplorer: false,
    showInTaskbar: true,
  },
  stats: {
    id: "stats",
    title: "Site Stats",
    icon: "📊",
    defaultWidth: 780,
    defaultHeight: 560,
    defaultX: 240,
    defaultY: 40,
    showInExplorer: false,
    showInTaskbar: true,
  },
  "image-viewer": {
    id: "image-viewer",
    title: "Image",
    icon: "🖼️",
    defaultWidth: 920,
    defaultHeight: 660,
    defaultX: 200,
    defaultY: 40,
    showInExplorer: false,
    showInTaskbar: true,
  },
  "search-result": {
    id: "search-result",
    title: "Search action complete",
    icon: "✨",
    defaultWidth: 360,
    defaultHeight: 160,
    defaultX: 600,
    defaultY: 80,
    showInExplorer: false,
    showInTaskbar: false,
  },
  "germany-notes": {
    id: "germany-notes",
    title: "germany-notes.txt",
    icon: "📄",
    defaultWidth: 760,
    defaultHeight: 520,
    defaultX: 250,
    defaultY: 40,
    showInExplorer: false,
    showInTaskbar: true,
  },
  "austria-notes": {
    id: "austria-notes",
    title: "austria-notes.txt",
    icon: "📄",
    defaultWidth: 760,
    defaultHeight: 520,
    defaultX: 270,
    defaultY: 60,
    showInExplorer: false,
    showInTaskbar: true,
  },
  "india-notes": {
    id: "india-notes",
    title: "india-notes.txt",
    icon: "📄",
    defaultWidth: 760,
    defaultHeight: 520,
    defaultX: 290,
    defaultY: 80,
    showInExplorer: false,
    showInTaskbar: true,
  },
};
